Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"  
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"    
  end
  config.vm.provision "shell", inline: "sudo apt-get update"  
  config.vm.provision "shell", privileged: false, path: "vagrant.sh"
end

